name: "🚀 Déploiement"

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: "📤 GitHub Pages"
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    steps:
      - name: Get source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: "pip"

      - name: Install dependencies
        env:
          GH_TOKEN_MATERIAL_INSIDERS: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python -m pip install --upgrade -r requirements.txt

      - name: Cache build dependencies (external assets downloaded)
        uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache

      - name: Build static website
        run: |
          mkdocs build --clean --config-file mkdocs.yml --verbose --strict

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "site"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4